version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tienda_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - tienda_net

  nginx:
    image: nginx:stable-alpine
    container_name: tienda_nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - tienda_net

  db:
    image: mysql:8.0
    container_name: tienda_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tienda
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: tienda
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - tienda_net

  redis:
    image: redis:alpine
    container_name: tienda_redis
    ports:
      - "6379:6379"
    networks:
      - tienda_net

volumes:
  dbdata:

networks:
  tienda_net: